version: 2

project_name: credscope

builds:
  - id: credscope
    main: ./cmd/credscope
    binary: credscope
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    mod_timestamp: '{{ if index .Env "CREDSCOPE_BUILD_TIMESTAMP" }}{{ index .Env "CREDSCOPE_BUILD_TIMESTAMP" }}{{ else }}{{ .CommitTimestamp }}{{ end }}'
    ldflags:
      - -s -w -buildid=
      - -X main.version=v{{ .Version }}
      - -X main.commit={{ if index .Env "CREDSCOPE_BUILD_COMMIT" }}{{ index .Env "CREDSCOPE_BUILD_COMMIT" }}{{ else }}{{ .FullCommit }}{{ end }}
      - -X main.date={{ .Env.BUILD_DATE }}

archives:
  - id: credscope
    ids: [credscope]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      owner: root
      group: root
      mode: 0755
      mtime: "{{ .Env.BUILD_DATE }}"
    files:
      - src: LICENSE
        info: &archive_file_info
          owner: root
          group: root
          mode: 0644
          mtime: "{{ .Env.BUILD_DATE }}"
      - src: README.md
        info: *archive_file_info
      - src: CHANGELOG.md
        info: *archive_file_info
    wrap_in_directory: true

metadata:
  mod_timestamp: '{{ if index .Env "CREDSCOPE_BUILD_TIMESTAMP" }}{{ index .Env "CREDSCOPE_BUILD_TIMESTAMP" }}{{ else }}{{ .CommitTimestamp }}{{ end }}'

checksum:
  name_template: checksums.txt
  algorithm: sha256

snapshot:
  version_template: '{{ if index .Env "CREDSCOPE_SNAPSHOT_VERSION" }}{{ index .Env "CREDSCOPE_SNAPSHOT_VERSION" }}{{ else }}{{ .Version }}-snapshot{{ end }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  prerelease: auto
